using System.Diagnostics;
using System.Text;

namespace PortfolioWorkflows;

public static class ReportTools
{
    private static readonly string ProjectDir =
        Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", ".."));
    private static readonly string ChartsDir = Path.Combine(ProjectDir, "charts");
    private static readonly string ReportsDir = InitReportsDir();

    private static string InitReportsDir()
    {
        var dir = Path.Combine(ProjectDir, "reports");
        Directory.CreateDirectory(dir);
        return dir;
    }

    public static string GenerateHtmlReport(string title, string content)
    {
        var timestamp = DateTime.Now.ToString("yyyyMMdd-HHmmss");
        var htmlPath = Path.Combine(ReportsDir, $"report-{timestamp}.html");

        var chartFiles = Directory.Exists(ChartsDir)
            ? Directory.GetFiles(ChartsDir, "*.html")
            : Array.Empty<string>();

        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang='en'><head>");
        sb.AppendLine($"<title>{System.Net.WebUtility.HtmlEncode(title)}</title>");
        sb.AppendLine("<meta charset='utf-8'>");
        sb.AppendLine("<style>");
        sb.AppendLine("body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; line-height: 1.7; color: #333; background: #fafafa; }");
        sb.AppendLine("h1 { color: #0078d4; border-bottom: 3px solid #0078d4; padding-bottom: 12px; }");
        sb.AppendLine("h2 { color: #106ebe; margin-top: 32px; }");
        sb.AppendLine("h3 { color: #444; }");
        sb.AppendLine(".chart-container { margin: 24px 0; }");
        sb.AppendLine(".chart-frame { width: 100%; height: 500px; border: 1px solid #ddd; border-radius: 8px; background: #fff; }");
        sb.AppendLine(".meta { color: #888; font-size: 0.9em; margin-bottom: 24px; }");
        sb.AppendLine("p { margin: 8px 0; }");
        sb.AppendLine("li { margin: 4px 0; }");
        sb.AppendLine(".footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; color: #888; font-size: 0.85em; }");
        sb.AppendLine("</style>");
        sb.AppendLine("</head><body>");
        sb.AppendLine($"<h1>📊 {System.Net.WebUtility.HtmlEncode(title)}</h1>");
        sb.AppendLine($"<p class='meta'>Generated on {DateTime.Now:MMMM dd, yyyy} at {DateTime.Now:h:mm tt}</p>");

        bool inList = false;
        foreach (var line in content.Split('\n'))
        {
            var t = line.TrimEnd();
            if (string.IsNullOrWhiteSpace(t))
            {
                if (inList) { sb.AppendLine("</ul>"); inList = false; }
                continue;
            }
            if (t.StartsWith("## "))
            {
                if (inList) { sb.AppendLine("</ul>"); inList = false; }
                sb.AppendLine($"<h2>{System.Net.WebUtility.HtmlEncode(t[3..])}</h2>");
            }
            else if (t.StartsWith("### "))
            {
                if (inList) { sb.AppendLine("</ul>"); inList = false; }
                sb.AppendLine($"<h3>{System.Net.WebUtility.HtmlEncode(t[4..])}</h3>");
            }
            else if (t.StartsWith("- ") || t.StartsWith("* "))
            {
                if (!inList) { sb.AppendLine("<ul>"); inList = true; }
                sb.AppendLine($"<li>{System.Net.WebUtility.HtmlEncode(t[2..])}</li>");
            }
            else
            {
                if (inList) { sb.AppendLine("</ul>"); inList = false; }
                var encoded = System.Net.WebUtility.HtmlEncode(t);
                encoded = System.Text.RegularExpressions.Regex.Replace(
                    encoded, @"\*\*(.+?)\*\*", "<strong>$1</strong>");
                sb.AppendLine($"<p>{encoded}</p>");
            }
        }
        if (inList) sb.AppendLine("</ul>");

        if (chartFiles.Length > 0)
        {
            sb.AppendLine("<h2>📈 Interactive Charts</h2>");
            foreach (var chart in chartFiles)
            {
                var name = Path.GetFileNameWithoutExtension(chart)
                    .Replace("-", " ").Replace("_", " ");
                var relativePath = Path.GetRelativePath(ReportsDir, chart).Replace('\\', '/');
                sb.AppendLine($"<div class='chart-container'>");
                sb.AppendLine($"<h3>{char.ToUpper(name[0])}{name[1..]}</h3>");
                sb.AppendLine($"<iframe class='chart-frame' src='{relativePath}' title='{name}'></iframe>");
                sb.AppendLine("</div>");
            }
        }

        sb.AppendLine($"<div class='footer'>Report generated by Portfolio Workflows — GitHub Copilot SDK + MAF</div>");
        sb.AppendLine("</body></html>");
        File.WriteAllText(htmlPath, sb.ToString());
        return htmlPath;
    }

    public static string? GeneratePdfReport(string title, string content)
    {
        var timestamp = DateTime.Now.ToString("yyyyMMdd-HHmmss");
        var pdfPath = Path.Combine(ReportsDir, $"report-{timestamp}.pdf");
        var mdPath = Path.Combine(ReportsDir, $".report-{timestamp}.md");

        try
        {
            var sb = new StringBuilder();
            sb.AppendLine("---");
            sb.AppendLine($"title: \"{title}\"");
            sb.AppendLine($"date: \"{DateTime.Now:MMMM dd, yyyy}\"");
            sb.AppendLine("---\n");
            sb.AppendLine(content);

            if (Directory.Exists(ChartsDir))
            {
                var pngs = Directory.GetFiles(ChartsDir, "*.png");
                if (pngs.Length > 0)
                {
                    sb.AppendLine("\n## Charts\n");
                    foreach (var png in pngs)
                    {
                        var name = Path.GetFileNameWithoutExtension(png)
                            .Replace("-", " ").Replace("_", " ");
                        sb.AppendLine($"### {char.ToUpper(name[0])}{name[1..]}");
                        sb.AppendLine($"![{name}]({png.Replace('\\', '/')})\n");
                    }
                }
            }

            File.WriteAllText(mdPath, sb.ToString());

            var psi = new ProcessStartInfo
            {
                FileName = "pandoc",
                Arguments = $"\"{mdPath}\" --pdf-engine=typst -o \"{pdfPath}\"",
                UseShellExecute = false,
                RedirectStandardError = true,
                CreateNoWindow = true
            };

            using var proc = Process.Start(psi);
            if (proc != null)
            {
                proc.WaitForExit(30_000);
                if (!proc.HasExited) proc.Kill();
            }

            try { File.Delete(mdPath); } catch { }
            return File.Exists(pdfPath) ? pdfPath : null;
        }
        catch
        {
            try { File.Delete(mdPath); } catch { }
            return null;
        }
    }
}
